version: "3.9"

services:
  backend:
    image: gogoadl247/spoparty-backend:latest
    container_name: backend
    tty: true
    restart: always
    ports:
      - "9090:9090"
    environment:
      - TZ=Asia/Seoul
    volume:
      - /opt/openvidu/recordings:/opt/openvidu/recordings
  batch:
    image: gogoadl247/spoparty-batch:latest
    container_name: batch
    tty: true
    restart: always
    ports:
      - "9091:9091"
    environment:
      - TZ=Asia/Seoul
  # frontend:
  #   image: gogoadl247/spoparty-frontend:latest
  #   container_name: frontend
  #   tty: true
  #   ports:
  #    - "3000:5173"
  # depends_on:
  #  - nginx
  # nginx:
  #   image: gogoadl247/spoparty-nginx:latest
  #   container_name: nginx
  #   user: root
  #   environment:
  #     - TZ=Asia/Seoul
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/nginx/sites-enabled/default:/etc/nginx/conf.d/default.conf
  #     - /etc/letsencrypt:/etc/letsencrypt
  #   ports:
  #     - "80:80"
  #     - "443:443"
  # jenkins:
  #   image: jenkins/jenkins:jdk17
  #   container_name: jenkins
  #   user: root
  #   environment:
  #     - JENKINS_OPTS=--httpPort=8080
  #     - TZ=Asia/Seoul
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /jenkins:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
  # openvidu:
  #   image: openvidu/openvidu-dev:2.29.0
  #   container_name: openvidu
  #   ports:
  #     - "4443:4443"
  #   environment:
  #     - OPENVIDU_SECRET=MY_SECRET
  #networks:
  #react-spring: {}
  #spring-mysql: {}
