server.port: 9091
sql:
  init:
    continue-on-error: true

spring:
  config.import: application-private.yml
  jpa:
#    database-platform: mariadb
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
#      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none
      jdbc:
        batch_size: 10
    properties:
      hibernate:
        format_sql: true
        show-sql: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never



#로거 찍기
logging:
  level:
#    org.hibernate.SQL: INFO
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace



