jpa:
  database-platform: mariadb
  show-sql: false
  hibernate:
    ddl-auto: none


  properties:
    hibernate:
      format_sql: true
sql:
  init:
    continue-on-error: true

spring:
  batch:
    jdbc:
      initialize-schema: never
  config.import: application-private.yml



#로거 찍기
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace