sql:
  init:
    continue-on-error: true

spring:
  config.import: application-private.yml
  jpa:
#    database-platform: mariadb
    show-sql: false
    hibernate:
#      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: never
  properties:
    hibernate:
      format_sql: true


#로거 찍기
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info