spring:
  config:
    activate:
      on-profile:
        - staging
        - prod
  datasource:
    batch:
      hikari:
        jdbc-url: jdbc:mariadb://spoparty-batch-db.ctm6ms0ey3dl.ap-northeast-2.rds.amazonaws.com:3306/spoparty_batch_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: admin
        password: ssafya802
        driver-class-name: org.mariadb.jdbc.Driver
        pool-name: 'read-and-write-pool'

