jpa:
  database-platform: mariadb
  show-sql: false
  hibernate:
    ddl-auto: none
sql:
  init:
    continue-on-error: true

spring:
  batch:
    jdbc:
      initialize-schema: never
  config.import: application-private.yml
