spring:
  meta:
    datasource:
      # 메타 정보 저장 DB
      hikari:
        username: admin
        password: ssafya802
        driver-class-name: org.mariadb.jdbc.Driver
        pool-name: 'meta-data-pool'
        jdbcurl: jdbc:mariadb://spoparty-batch-db.ctm6ms0ey3dl.ap-northeast-2.rds.amazonaws.com:3306/spoparty_batch_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    # 처리 데이터 소스
  default:
    datasource:
      hikari:
        #        username: admin
        #        password: ssafya802
        #        driver-class-name: org.mariadb.jdbc.Driver
        #        pool-name: 'read-and-write-pool'
        #        jdbcurl: jdbc:mariadb://spoparty-database.cpqorrmhxcvs.ap-northeast-2.rds.amazonaws.com:3306/spoparty?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: S10P12A802
        password: 6DcwoD2dA
        driver-class-name: org.mariadb.jdbc.Driver
        pool-name: 'read-and-write-pool'
        jdbcurl: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P12A802?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8



api-key: 95920a4c5a228f3edfd581cf9cd299a8
api-host: v3.football.api-sports.io
base-url: https://v3.football.api-sports.io

lang-secret: uBDc7x2dwu
lang-id: xCLhObLuJ8ob43b93ziu
lang-base-url: https://openapi.naver.com/v1/papago/n2mt