# Datasource
spring:
  config:
    activate:
      on-profile: private
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: admin
      password: ssafya802
    url: jdbc:mariadb://spoparty-database.cpqorrmhxcvs.ap-northeast-2.rds.amazonaws.com:3306/spoparty?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8

  # Smtp
  mail:
    host: smtp.gmail.com
    port: 587
    username: spoparty123@gmail.com
    password: tjbp bgca mree laud
    properties:
      mail:
        smtp:
          auth: true # Autentication
          timeout: 5000 # Socket Read Timeout (ms)
          starttls:
            enable: true # StartTLS

  # OAuth2 kakao
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: e6eaf57a86c5a93933a23dd63e73c44e
            client-secret: bTZG4U0KETlDHaeaLuQEqpnuaNoC6wvZ
            redirect-uri: http://localhost:9090/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email



# Smtp mail content
smtp:
  mail:
    subject: "SPOPARTY 이메일 인증"
    prefix: "# 인증번호 : "
    suffix: "\n 5분안에 입력해주세요"



# Jwt 1hour / 15day
jwt:
  access:
    secret: dyAeHub00pwL4F2Lcse52l1z5A003L3Bjtw4lcq751tymZvvqkcEU7L1imkKHeDa
    expiration: 3600000
  refresh:
    secret: syLzLe230fFXO0OfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymCL1ctob5dlwoqhvhDa
    expiration: 1269600000

# S3
cloud:
  aws:
    s3:
      bucket: spoparty-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: access
      secretKey: secret

openvidu:
  url: https://i10a802.p.ssafy.io/
  secret: MY_SECRET
